---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rancher-web
  name: rancher-web-test-deployment
  labels:
    app: rancher-web-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rancher-web-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rancher-web-test
    spec:
      affinity:
        podAffinity: {}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector: {}
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - image: httpd:2.4
        imagePullPolicy: Always
        name: rancher-web-test
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs
          name: webroot
          subPath: rancherweb1/htdocs
        - mountPath: /usr/local/apache2/conf
          name: webroot
          subPath: rancherweb1/conf      
      volumes:
      - name: webroot
        persistentVolumeClaim:
          claimName: rancher-web-pvclaim
