---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: rancher-web-ingress
  namespace: default
spec:
  rules:
  - host: rancherweb.kube.rmntest.com
    http:
      paths:
      - backend:
          service:
            name: rancher-web-service
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: rancher-web-test-service
            port:
              number: 80
        path: /test(/|$)(.*)
        pathType: Prefix